version: '3.2'
volumes:
  dbdata:
services:
  db:
    image: postgres:9.6-alpine
  web:
    image: govukdfe/manage-courses-backend-semaphore:$GIT_SHORT_SHA
    command: sh -c "bundle exec rails server -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=postgres
