authentication:
  algorithm: HS256
  # Set this in the env! The below ensures that we are un-authenticatable if we
  # forget to do this in production.
  secret: <%= SecureRandom.base64 %>
current_recruitment_cycle_year: 2020
allocation_cycle_year: 2020
govuk_notify:
  api_key: please_change_me
  welcome_email_template_id: please_change_me
  course_update_email_template_id: please_change_me
  course_publish_email_template_id: please_change_me
  magic_link_email_template_id: please_change_me
  course_withdraw_email_template_id: please_change_me
  course_vacancies_filled_email_template_id: please_change_me
  subject_update_email_template_id: please_change_me
publish_url: http://localhost:3000
find_url: http://localhost:3002
mcbg:
  redis_password: <%= SecureRandom.base64 %>
system_authentication_token: <%= SecureRandom.base64 %>
application: teacher-training-api
logstash:
  type: tcp
  host: # Our hostname here
  port: # Our port here
  ssl_enable: true
log_level: info
magic_link:
  max_token_age: <%= 1.hour %>
commit_sha_file: COMMIT_SHA
skylight:
  enable: false
  authentication: please_change_me
