gcp_api_key: please_change_me
publish_url: https://www.publish-teacher-training-courses.service.gov.uk
find_url: https://www2.find-postgraduate-teacher-training.service.gov.uk
bg_jobs:
  save_statistic:
    cron: "0 0 * * *" # daily at midnight
    class: "SaveStatisticJob"
    queue: save_statistic
skylight:
  enable: false
